service:
  http_port: 6333
  grpc_port: 6334

storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots

# 성능 최적화
optimizer:
  # 색인 임계값
  indexing_threshold: 20000
  
  # 최대 세그먼트 크기
  max_segment_size: 200000

# 리소스 제한
cluster:
  enabled: false

# 보안 설정
# tls:
#   enabled: true
#   cert: /path/to/cert.pem
#   key: /path/to/key.pem
